"""
turbofan.py
Port of the CF34 deck interpolation logic from episod_5_results_and_lookup_table.ipynb
(flight-test-engineering/Gas-Turbine-Propulsion).

Uses the pre-computed CF34_deck_v4.csv generated by pyCycle / OpenMDAO.
Performs trilinear interpolation over (altitude, Mach, PC) with boundary
extrapolation at the edges of the table.
"""

from __future__ import annotations
import os
import pandas as pd
import numpy as np

# ── Load deck once at module import ─────────────────────────────────────────
_BACKEND_DIR = os.path.dirname(os.path.abspath(__file__))  # BUG-7 fix: abspath so never empty
_DECK_PATH   = os.path.join(_BACKEND_DIR, "..", "data", "CF34_deck_v4.csv")

# Fallback: deck placed alongside backend files (flat layout)
if not os.path.exists(_DECK_PATH):
    _DECK_PATH = os.path.join(_BACKEND_DIR, "CF34_deck_v4.csv")

def _load_deck(path: str) -> pd.DataFrame:
    df = pd.read_csv(path, header=0)
    # Remove the known anomalous 19 000 ft data (pyCycle bug #96)
    df = df[(df["alt"] < 18_999) | (df["alt"] > 20_001)].copy()
    df.reset_index(drop=True, inplace=True)
    return df

DF_CF34: pd.DataFrame = _load_deck(_DECK_PATH)

# ── Key columns exposed to the API ──────────────────────────────────────────
KEY_OUTPUTS = [
    "Fn",     # net thrust [lbf]
    "Fg",     # gross thrust [lbf]
    "F_ram",  # ram drag [lbf]
    "TSFC",   # thrust-specific fuel consumption [lbm/(lbf·h)]
    "BPR",    # bypass ratio
    "Wf",     # fuel flow [lbm/s]
    "OPR",    # overall pressure ratio
    "FAR",    # fuel-air ratio
    "N1",     # LP spool speed [rpm or corrected]
    "N2",     # HP spool speed
    "burner:tot:T",  # turbine inlet temperature [R]
    "hpc:tot:T",     # HPC exit temperature [R]
    "lpt:tot:T",     # LPT exit temperature [R]
    "fan:tot:P",     # fan exit total pressure [atm]
    "hpc:tot:P",     # HPC exit total pressure [atm]
]

# ── Deck envelope (for frontend range validation) ────────────────────────────
ENVELOPE = {
    "alt_ft": {
        "min": float(DF_CF34["alt"].min()),
        "max": float(DF_CF34["alt"].max()),
        "unique_count": int(DF_CF34["alt"].nunique()),
    },
    "PC": {
        "min": float(DF_CF34["PC"].min()),
        "max": float(DF_CF34["PC"].max()),
        "values": sorted(DF_CF34["PC"].unique().tolist()),
    },
    "MN_approx": {
        "description": "Deck contains computed (non-round) Mach values. Interpolation handles any MN in range.",
        "min": float(DF_CF34["MN"].min()),
        "max": float(DF_CF34["MN"].max()),
    },
}


# ─────────────────────────────────────────────────────────────────────────────
# Interpolation helpers (exact port from episod_5 notebook)
# ─────────────────────────────────────────────────────────────────────────────

def _get_bracket(target: float, val_list) -> tuple[float, float]:
    """Return the nearest lower and upper neighbours of target in val_list."""
    highs = [x for x in val_list if x >= target]
    lows  = [x for x in val_list if x <  target]

    high_val = min(highs) if highs else max(val_list)
    low_val  = max(lows)  if lows  else min(val_list)
    return low_val, high_val


def _adjust_limits(val: float, val_list: list) -> tuple[float, float]:
    """When target is outside the table, use the two nearest edge points."""
    if abs(val - val_list[0]) > abs(val - val_list[-1]):
        return val_list[-2], val_list[-1]
    else:
        return val_list[0], val_list[1]


def _linear_interp(
    x: float,
    x2: float, x1: float,
    y2, y1,
) -> np.ndarray:
    """Simple 1-D linear interpolation between two array-valued points."""
    if x2 == x1:
        return (y2 + y1) / 2.0
    m  = (y2 - y1) / (x2 - x1)
    x0 = y1 - m * x1
    return m * x + x0


def interp_altMNPC(
    Hp: float,
    MN: float,
    PC: float,
    df: pd.DataFrame | None = None,
) -> dict:
    """
    Trilinearly interpolate the CF34 deck at a given (altitude, Mach, power).

    Parameters
    ----------
    Hp  : pressure altitude [ft]
    MN  : Mach number
    PC  : power code — fraction of max power (0.55 … 1.0)
    df  : dataframe to use (defaults to the pre-loaded CF34 deck)

    Returns
    -------
    dict mapping each column name → interpolated scalar value
    """
    if df is None:
        df = DF_CF34

    # Build altitude→Mach lookup
    alts   = df["alt"].unique()
    alt_MN = {alt: df[df["alt"] == alt]["MN"].unique().tolist() for alt in alts}
    PCs    = sorted(df[(df["alt"] == df["alt"].iloc[0]) & 
                       (df["MN"]  == df["MN"].iloc[0])]["PC"].unique().tolist())

    col_names = df.columns.tolist()

    # ── Altitude bracket ────────────────────────────────────────────────────
    pt = {
        "low":  {"alt": 0, "M_low": 0, "M_high": 0},
        "high": {"alt": 0, "M_low": 0, "M_high": 0},
    }
    pt["low"]["alt"], pt["high"]["alt"] = _get_bracket(Hp, alt_MN.keys())

    if pt["low"]["alt"] == pt["high"]["alt"]:
        alt_list = sorted(alt_MN.keys())
        pt["low"]["alt"], pt["high"]["alt"] = _adjust_limits(Hp, alt_list)

    # ── Mach bracket for each altitude ─────────────────────────────────────
    for lh in ["low", "high"]:
        M_low, M_high = _get_bracket(MN, alt_MN[pt[lh]["alt"]])
        if M_low == M_high:
            MN_list = sorted(alt_MN[pt[lh]["alt"]])
            M_low, M_high = _adjust_limits(MN, MN_list)
        pt[lh]["M_low"]  = M_low
        pt[lh]["M_high"] = M_high

    # ── PC bracket ─────────────────────────────────────────────────────────
    PC_low, PC_high = _get_bracket(PC, PCs)
    if PC_low == PC_high:
        PC_low, PC_high = _adjust_limits(PC, PCs)

    # ── Extract corner numpy arrays ─────────────────────────────────────────
    interp_pts = []
    for lh in ["high", "low"]:
        for mh in ["M_high", "M_low"]:
            arr = df.query(
                f"alt == {pt[lh]['alt']} and MN == {pt[lh][mh]}"
            ).to_numpy()
            interp_pts.append(arr)

    # ── Interpolate PC ──────────────────────────────────────────────────────
    pc_idx = col_names.index("PC")
    temp_pts = []
    for arr in interp_pts:
        y2 = arr[np.where(arr[:, pc_idx] == PC_high)]
        y1 = arr[np.where(arr[:, pc_idx] == PC_low)]
        temp_pts.append(_linear_interp(PC, PC_high, PC_low, y2, y1))

    # ── Interpolate Mach ────────────────────────────────────────────────────
    temp_pts2 = []
    for idx, lh in enumerate(["high", "low"]):
        x2  = pt[lh]["M_high"]
        x1  = pt[lh]["M_low"]
        y2  = temp_pts[2 * idx]
        y1  = temp_pts[2 * idx + 1]
        temp_pts2.append(_linear_interp(MN, x2, x1, y2, y1))

    # ── Interpolate altitude ────────────────────────────────────────────────
    x2          = pt["high"]["alt"]
    x1          = pt["low"]["alt"]
    interp_data = _linear_interp(Hp, x2, x1, temp_pts2[0], temp_pts2[1])

    return {col: float(interp_data[0][i]) for i, col in enumerate(col_names)}


def get_envelope() -> dict:
    """Return the flight envelope information for the CF34 deck."""
    return ENVELOPE
